import { listAlerts, getAlertCounts } from "@/services/alert.service";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { AlertsList } from "@/components/business-intelligence/alerts-list";
import { RunAlertScanButton } from "@/components/business-intelligence/run-alert-scan-button";

export const metadata = { title: "Alerts Center | Zarghoon Jewellers" };

const STATUS_FILTERS = ["OPEN", "ACKNOWLEDGED", "RESOLVED", "DISMISSED"] as const;

export default async function AlertsCenterPage({
  searchParams,
}: {
  searchParams: Promise<Record<string, string | undefined>>;
}) {
  const params = await searchParams;
  const status = STATUS_FILTERS.includes(params.status as (typeof STATUS_FILTERS)[number])
    ? (params.status as (typeof STATUS_FILTERS)[number])
    : "OPEN";

  const [alerts, counts] = await Promise.all([listAlerts({ status }, 100), getAlertCounts()]);

  return (
    <div className="flex flex-1 flex-col gap-6 p-4 sm:p-6">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <div>
          <h1 className="font-display text-xl font-semibold text-foreground">Alerts Center</h1>
          <p className="text-sm text-muted-foreground">Every alert is generated by a deterministic rule — nothing here modifies data automatically.</p>
        </div>
        <RunAlertScanButton />
      </div>

      <Card>
        <CardContent className="flex flex-wrap gap-2 py-4">
          {STATUS_FILTERS.map((s) => (
            <a
              key={s}
              href={`/business-intelligence/alerts?status=${s}`}
              className="rounded-full border border-border px-3 py-1 text-xs font-medium text-muted-foreground transition-colors hover:text-foreground data-[active=true]:border-gold data-[active=true]:text-gold"
              data-active={s === status}
            >
              {s} <Badge variant="neutral">{counts[s]}</Badge>
            </a>
          ))}
        </CardContent>
      </Card>

      <AlertsList alerts={alerts} />
    </div>
  );
}
