"""Static seed data for assets and the 10 selectable strategies.

Used by scripts/seed.py (idempotent upsert) and by tests / strategy registry
defaults. Editing this file does not change already-seeded rows in the
database; use the admin API or re-run the seed script to apply updates.
"""

from app.models.enums import AssetType

ASSETS: list[dict] = [
    {
        "symbol": "EUR/USD",
        "provider_symbol": "EUR/USD",
        "display_name": "Euro / US Dollar",
        "asset_type": AssetType.FOREX,
        "pip_precision": 5,
    },
    {
        "symbol": "GBP/USD",
        "provider_symbol": "GBP/USD",
        "display_name": "British Pound / US Dollar",
        "asset_type": AssetType.FOREX,
        "pip_precision": 5,
    },
    {
        "symbol": "USD/JPY",
        "provider_symbol": "USD/JPY",
        "display_name": "US Dollar / Japanese Yen",
        "asset_type": AssetType.FOREX,
        "pip_precision": 3,
    },
    {
        "symbol": "AUD/USD",
        "provider_symbol": "AUD/USD",
        "display_name": "Australian Dollar / US Dollar",
        "asset_type": AssetType.FOREX,
        "pip_precision": 5,
    },
    {
        "symbol": "USD/CAD",
        "provider_symbol": "USD/CAD",
        "display_name": "US Dollar / Canadian Dollar",
        "asset_type": AssetType.FOREX,
        "pip_precision": 5,
    },
    {
        "symbol": "EUR/JPY",
        "provider_symbol": "EUR/JPY",
        "display_name": "Euro / Japanese Yen",
        "asset_type": AssetType.FOREX,
        "pip_precision": 3,
    },
    {
        "symbol": "GBP/JPY",
        "provider_symbol": "GBP/JPY",
        "display_name": "British Pound / Japanese Yen",
        "asset_type": AssetType.FOREX,
        "pip_precision": 3,
    },
    {
        "symbol": "EUR/GBP",
        "provider_symbol": "EUR/GBP",
        "display_name": "Euro / British Pound",
        "asset_type": AssetType.FOREX,
        "pip_precision": 5,
    },
    {
        "symbol": "XAU/USD",
        "provider_symbol": "XAU/USD",
        "display_name": "Gold / US Dollar",
        "asset_type": AssetType.COMMODITY,
        "pip_precision": 2,
    },
    {
        "symbol": "BTC/USD",
        "provider_symbol": "BTC/USD",
        "display_name": "Bitcoin / US Dollar",
        "asset_type": AssetType.CRYPTO,
        "pip_precision": 2,
    },
    {
        "symbol": "ETH/USD",
        "provider_symbol": "ETH/USD",
        "display_name": "Ethereum / US Dollar",
        "asset_type": AssetType.CRYPTO,
        "pip_precision": 2,
    },
]

# All expiries the platform supports, in seconds. Availability per-provider is
# gated at runtime by app/services/market_data/capabilities.py.
ALL_EXPIRIES = [15, 30, 60, 120, 180, 300]
ALL_TIMEFRAMES = ["1m", "5m", "15m"]

STRATEGIES: list[dict] = [
    {
        "strategy_code": "ema_trend_pullback",
        "name": "EMA Trend Pullback",
        "description": "Enters in the direction of a confirmed EMA trend (9/21/50/200) after a controlled pullback and bullish/bearish rejection candle, provided market structure and ATR remain favorable.",
        "version": 1,
        "configuration_json": {
            "ema_fast": 9,
            "ema_mid": 21,
            "ema_slow": 50,
            "ema_trend": 200,
            "atr_period": 14,
            "atr_min_pct": 0.02,
            "atr_max_pct": 3.0,
            "pullback_atr_multiple": 1.2,
            "min_body_ratio": 0.35,
            "sr_buffer_atr_multiple": 0.5,
        },
        "supported_assets_json": [],
        "supported_timeframes_json": ["1m", "5m", "15m"],
        "supported_expiries_json": [60, 120, 180, 300],
        "risk_level": "medium",
    },
    {
        "strategy_code": "ema_crossover_momentum",
        "name": "EMA Crossover Momentum",
        "description": "Detects a fresh EMA(9/21) crossover confirmed by MACD histogram expansion and RSI momentum, rejecting late entries after an extended move.",
        "version": 1,
        "configuration_json": {
            "ema_fast": 9,
            "ema_mid": 21,
            "ema_slow": 50,
            "rsi_period": 14,
            "macd_fast": 12,
            "macd_slow": 26,
            "macd_signal": 9,
            "max_bars_since_cross": 3,
            "atr_period": 14,
            "sr_buffer_atr_multiple": 0.6,
        },
        "supported_assets_json": [],
        "supported_timeframes_json": ["1m", "5m", "15m"],
        "supported_expiries_json": [30, 60, 120, 180, 300],
        "risk_level": "medium",
    },
    {
        "strategy_code": "support_resistance_rejection",
        "name": "Support & Resistance Rejection",
        "description": "Generates a reversal signal when price tests a multiple-touch support or resistance level and closes back through it with a strong rejection wick.",
        "version": 1,
        "configuration_json": {
            "swing_lookback": 40,
            "min_touches": 2,
            "wick_body_ratio_min": 1.5,
            "atr_period": 14,
            "level_tolerance_atr_multiple": 0.3,
        },
        "supported_assets_json": [],
        "supported_timeframes_json": ["1m", "5m", "15m"],
        "supported_expiries_json": [30, 60, 120, 180, 300],
        "risk_level": "medium",
    },
    {
        "strategy_code": "breakout_retest",
        "name": "Breakout & Retest",
        "description": "Trades continuation after a confirmed breakout candle closes beyond support/resistance and price successfully retests the broken level with directional rejection.",
        "version": 1,
        "configuration_json": {
            "swing_lookback": 40,
            "breakout_body_atr_multiple": 1.1,
            "retest_tolerance_atr_multiple": 0.35,
            "max_bars_to_retest": 8,
            "atr_period": 14,
        },
        "supported_assets_json": [],
        "supported_timeframes_json": ["1m", "5m", "15m"],
        "supported_expiries_json": [60, 120, 180, 300],
        "risk_level": "high",
    },
    {
        "strategy_code": "liquidity_sweep_reversal",
        "name": "Liquidity Sweep Reversal",
        "description": "Detects stop-hunt sweeps beyond recent swing highs/lows followed by a fast reclaim, significant wick and bullish/bearish confirmation candle.",
        "version": 1,
        "configuration_json": {
            "swing_lookback": 30,
            "sweep_wick_atr_multiple": 0.8,
            "reclaim_max_bars": 3,
            "atr_period": 14,
            "min_atr_pct": 0.03,
        },
        "supported_assets_json": [],
        "supported_timeframes_json": ["1m", "5m", "15m"],
        "supported_expiries_json": [30, 60, 120, 180, 300],
        "risk_level": "high",
    },
    {
        "strategy_code": "rsi_divergence_reversal",
        "name": "RSI Divergence Reversal",
        "description": "Detects regular/hidden RSI(14) divergence at meaningful support or resistance, requiring both level confluence and candle confirmation before signaling.",
        "version": 1,
        "configuration_json": {
            "rsi_period": 14,
            "swing_lookback": 30,
            "atr_period": 14,
            "allow_hidden_divergence": True,
            "level_tolerance_atr_multiple": 0.4,
        },
        "supported_assets_json": [],
        "supported_timeframes_json": ["1m", "5m", "15m"],
        "supported_expiries_json": [60, 120, 180, 300],
        "risk_level": "medium",
    },
    {
        "strategy_code": "bollinger_squeeze_breakout",
        "name": "Bollinger Squeeze Breakout",
        "description": "Detects Bollinger Band compression (low band-width percentile) followed by expansion and a strong directional close beyond the bands, rejecting false-breakout wicks.",
        "version": 1,
        "configuration_json": {
            "bb_period": 20,
            "bb_std": 2.0,
            "squeeze_percentile": 20,
            "atr_period": 14,
            "ema_trend": 50,
            "opposite_wick_max_ratio": 0.4,
        },
        "supported_assets_json": [],
        "supported_timeframes_json": ["1m", "5m", "15m"],
        "supported_expiries_json": [60, 120, 180, 300],
        "risk_level": "high",
    },
    {
        "strategy_code": "macd_momentum_continuation",
        "name": "MACD Momentum Continuation",
        "description": "Trades short-term continuation when EMA trend alignment, MACD histogram expansion and RSI are aligned and no opposing level sits nearby.",
        "version": 1,
        "configuration_json": {
            "ema_mid": 21,
            "ema_slow": 50,
            "rsi_period": 14,
            "macd_fast": 12,
            "macd_slow": 26,
            "macd_signal": 9,
            "rsi_extreme_high": 75,
            "rsi_extreme_low": 25,
            "atr_period": 14,
        },
        "supported_assets_json": [],
        "supported_timeframes_json": ["1m", "5m", "15m"],
        "supported_expiries_json": [30, 60, 120, 180, 300],
        "risk_level": "medium",
    },
    {
        "strategy_code": "candlestick_price_action",
        "name": "Candlestick Price Action",
        "description": "Generates signals from professional candlestick patterns (engulfing, hammer, shooting star, morning/evening star, pin bar, inside/outside bar) only when trend or S/R context and volatility support them.",
        "version": 1,
        "configuration_json": {
            "atr_period": 14,
            "min_body_ratio": 0.3,
            "min_wick_ratio": 1.5,
            "sr_buffer_atr_multiple": 0.5,
        },
        "supported_assets_json": [],
        "supported_timeframes_json": ["1m", "5m", "15m"],
        "supported_expiries_json": [15, 30, 60, 120, 180, 300],
        "risk_level": "medium",
    },
    {
        "strategy_code": "multi_timeframe_confluence",
        "name": "Multi-Timeframe Confluence",
        "description": "Uses a higher timeframe for major trend, a confirmation timeframe for structure and an entry timeframe for timing; rejects the signal when timeframes conflict.",
        "version": 1,
        "configuration_json": {
            "higher_timeframe": "15m",
            "confirmation_timeframe": "5m",
            "entry_timeframe": "1m",
            "ema_fast": 9,
            "ema_mid": 21,
            "ema_slow": 50,
            "atr_period": 14,
        },
        "supported_assets_json": [],
        "supported_timeframes_json": ["1m"],
        "supported_expiries_json": [60, 120, 180, 300],
        "risk_level": "low",
    },
]
