using FXVolumeTrader.Core.Enums;

namespace FXVolumeTrader.Core.Models;

/// <summary>
/// A request to open a trade, submitted to an ITradeExecutionProvider.
/// For ManualConfirmationExecutionProvider this represents what the user
/// is shown and manually confirms - it is never auto-submitted to a broker.
/// </summary>
public sealed class TradeRequest
{
    public required string Symbol { get; init; }

    public required TradeDirection Direction { get; init; }

    public required decimal Amount { get; init; }

    public required ExpiryType Expiry { get; init; }

    public required TimeframeType Timeframe { get; init; }

    public int? SignalConfidence { get; init; }

    public string? SignalReason { get; init; }

    /// <summary>Idempotency key generated by the caller to prevent duplicate submissions.</summary>
    public required string ClientRequestId { get; init; }

    public required TradingMode Mode { get; init; }
}
