<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>FXVolumeTrader.Core</RootNamespace>
    <AssemblyName>FXVolumeTrader.Core</AssemblyName>
    <LangVersion>latest</LangVersion>
    <WarningsAsErrors>false</WarningsAsErrors>
  </PropertyGroup>

</Project>
