<?php
/**
 * Zarghoon Jewellers - Database Connection
 *
 * Secure PDO connection (singleton) plus a small set of reusable
 * database helper functions used throughout the project. Every query
 * in this project must go through PDO prepared statements - user input
 * must never be concatenated directly into SQL.
 */

require_once __DIR__ . '/config.php';

// ---------------------------------------------------------------
// Database credentials
// ---------------------------------------------------------------
// Prefer environment variables when the host provides them (common on
// managed hosting), falling back to these defaults for local/cPanel use.
define('DB_HOST', getenv('DB_HOST') ?: 'localhost');
define('DB_NAME', getenv('DB_NAME') ?: 'zarghoon_jewellers');
define('DB_USER', getenv('DB_USER') ?: 'root');
define('DB_PASS', getenv('DB_PASS') ?: '');
define('DB_CHARSET', 'utf8mb4');

/**
 * Returns a shared PDO connection instance (created once per request).
 */
function db(): PDO
{
    static $pdo = null;

    if ($pdo === null) {
        $dsn = 'mysql:host=' . DB_HOST . ';dbname=' . DB_NAME . ';charset=' . DB_CHARSET;
        $options = [
            PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
            PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
            PDO::ATTR_EMULATE_PREPARES => false,
        ];

        try {
            $pdo = new PDO($dsn, DB_USER, DB_PASS, $options);
        } catch (PDOException $e) {
            error_log('Database connection failed: ' . $e->getMessage());
            http_response_code(500);
            if (APP_DEBUG) {
                die('Database connection failed: ' . htmlspecialchars($e->getMessage(), ENT_QUOTES, 'UTF-8'));
            }
            die('We are experiencing a technical issue. Please try again shortly.');
        }
    }

    return $pdo;
}

// ---------------------------------------------------------------
// Reusable database helper functions
// All of these use prepared statements with bound parameters - never
// pass raw, un-parameterized user input into $sql.
// ---------------------------------------------------------------

/**
 * Run a SELECT and return every matching row as an associative array.
 */
function dbFetchAll(string $sql, array $params = []): array
{
    $stmt = db()->prepare($sql);
    $stmt->execute($params);
    return $stmt->fetchAll();
}

/**
 * Run a SELECT and return the first matching row, or null if none found.
 */
function dbFetchOne(string $sql, array $params = []): ?array
{
    $stmt = db()->prepare($sql);
    $stmt->execute($params);
    $row = $stmt->fetch();
    return $row === false ? null : $row;
}

/**
 * Run a SELECT and return a single scalar value (e.g. COUNT(*)), or null.
 */
function dbFetchColumn(string $sql, array $params = [])
{
    $stmt = db()->prepare($sql);
    $stmt->execute($params);
    $value = $stmt->fetchColumn();
    return $value === false ? null : $value;
}

/**
 * Run an INSERT/UPDATE/DELETE statement. Returns true on success.
 */
function dbExecute(string $sql, array $params = []): bool
{
    $stmt = db()->prepare($sql);
    return $stmt->execute($params);
}

/**
 * Returns the auto-increment ID generated by the most recent INSERT.
 */
function dbInsertId(): string
{
    return db()->lastInsertId();
}

/**
 * Runs a callback inside a database transaction. The callback's return
 * value is passed through on success; on any exception the transaction
 * is rolled back and the exception is re-thrown to the caller.
 */
function dbTransaction(callable $callback)
{
    $pdo = db();
    $pdo->beginTransaction();
    try {
        $result = $callback($pdo);
        $pdo->commit();
        return $result;
    } catch (Throwable $e) {
        $pdo->rollBack();
        throw $e;
    }
}
