// <auto-generated />
using System;
using FXVolumeTrader.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FXVolumeTrader.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("FXVolumeTrader.Infrastructure.Data.Entities.AppSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("AppSettings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "General",
                            Description = "Demo/paper mode is enabled by default for safety.",
                            Key = "App.DemoModeEnabled",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "true"
                        },
                        new
                        {
                            Id = 2,
                            Category = "General",
                            Description = "Startup trading mode.",
                            Key = "App.DefaultTradingMode",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "LiveSignalOnly"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Appearance",
                            Description = "Application theme.",
                            Key = "App.Theme",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "Dark"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Risk",
                            Description = "Maximum daily loss before trading is halted.",
                            Key = "Risk.MaxDailyLoss",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "50"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Risk",
                            Description = "Daily profit target (informational stop point).",
                            Key = "Risk.DailyProfitTarget",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "100"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Risk",
                            Description = "Maximum number of trades allowed per day.",
                            Key = "Risk.MaxTradesPerDay",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "20"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Risk",
                            Description = "Maximum number of trades allowed per session.",
                            Key = "Risk.MaxTradesPerSession",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "10"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Risk",
                            Description = "Consecutive losses before a cooldown is enforced.",
                            Key = "Risk.ConsecutiveLossLimit",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "3"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Risk",
                            Description = "Cooldown period after a loss.",
                            Key = "Risk.CooldownAfterLossSeconds",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "300"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Risk",
                            Description = "Cooldown period after any signal is issued.",
                            Key = "Risk.CooldownAfterSignalSeconds",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "15"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Risk",
                            Description = "Fixed trade amount used when percentage-based risk is disabled.",
                            Key = "Risk.FixedTradeAmount",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "1"
                        },
                        new
                        {
                            Id = 12,
                            Category = "Risk",
                            Description = "Hard ceiling on any single trade amount.",
                            Key = "Risk.MaxTradeAmount",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "25"
                        },
                        new
                        {
                            Id = 13,
                            Category = "Risk",
                            Description = "Optional loss-recovery sizing system. Disabled by default - increases risk when enabled.",
                            Key = "Risk.RecoverySystemEnabled",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "false"
                        },
                        new
                        {
                            Id = 14,
                            Category = "Notifications",
                            Description = "Show a desktop notification when a new signal is generated.",
                            Key = "Notifications.DesktopEnabled",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "true"
                        },
                        new
                        {
                            Id = 15,
                            Category = "Notifications",
                            Description = "Play a sound alert when a new signal is generated.",
                            Key = "Notifications.SoundEnabled",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "true"
                        },
                        new
                        {
                            Id = 16,
                            Category = "Compliance",
                            Description = "Whether the user has acknowledged the risk warning / no-guarantee disclaimer.",
                            Key = "Compliance.DisclaimerAcknowledged",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "false"
                        });
                });

            modelBuilder.Entity("FXVolumeTrader.Infrastructure.Data.Entities.ApplicationLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Exception")
                        .HasColumnType("TEXT");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceContext")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TimestampUtc");

                    b.ToTable("ApplicationLogs", (string)null);
                });

            modelBuilder.Entity("FXVolumeTrader.Infrastructure.Data.Entities.Backtest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AverageConfidence")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateRangeEndUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateRangeStartUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Draws")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExecutionDelayMs")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("GrossLoss")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("GrossProfit")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<int>("Losses")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MaxDrawdown")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NetResult")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PayoutPercentage")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ProfitFactor")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<int>("SignalDelayMs")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SlippagePips")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SpreadPips")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("StrategyConfigurationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalTrades")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("WinRate")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<int>("Wins")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StrategyConfigurationId");

                    b.ToTable("Backtests", (string)null);
                });

            modelBuilder.Entity("FXVolumeTrader.Infrastructure.Data.Entities.BacktestTrade", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Asset")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int>("BacktestId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Confidence")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Direction")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("EntryPrice")
                        .HasPrecision(18, 8)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ExitPrice")
                        .HasPrecision(18, 8)
                        .HasColumnType("TEXT");

                    b.Property<int>("Expiry")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Payout")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ProfitLoss")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("Result")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Timeframe")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BacktestId");

                    b.ToTable("BacktestTrades", (string)null);
                });

            modelBuilder.Entity("FXVolumeTrader.Infrastructure.Data.Entities.Candle", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AverageSpread")
                        .HasColumnType("TEXT");

                    b.Property<int>("BearishTicks")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BullishTicks")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Close")
                        .HasPrecision(18, 8)
                        .HasColumnType("TEXT");

                    b.Property<string>("DataSource")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndTimeUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("High")
                        .HasPrecision(18, 8)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFinalized")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Low")
                        .HasPrecision(18, 8)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MaximumSpread")
                        .HasColumnType("TEXT");

                    b.Property<int>("NeutralTicks")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Open")
                        .HasPrecision(18, 8)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PriceVelocity")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTimeUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int>("TickVolume")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Timeframe")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("VolumeVelocity")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Symbol", "Timeframe", "StartTimeUtc")
                        .IsUnique();

                    b.ToTable("Candles", (string)null);
                });

            modelBuilder.Entity("FXVolumeTrader.Infrastructure.Data.Entities.RiskEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EventType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TradingSessionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAtUtc");

                    b.HasIndex("TradingSessionId");

                    b.ToTable("RiskEvents", (string)null);
                });

            modelBuilder.Entity("FXVolumeTrader.Infrastructure.Data.Entities.Signal", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CandleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConfidenceScore")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Expiry")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MarketCondition")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SignalType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StrategyVersion")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int>("Timeframe")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TradingSessionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CandleId");

                    b.HasIndex("TradingSessionId");

                    b.HasIndex("Symbol", "CreatedAtUtc");

                    b.ToTable("Signals", (string)null);
                });

            modelBuilder.Entity("FXVolumeTrader.Infrastructure.Data.Entities.SignalScoreComponent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ComponentName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Explanation")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SignalId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SignalId");

                    b.ToTable("SignalScoreComponents", (string)null);
                });

            modelBuilder.Entity("FXVolumeTrader.Infrastructure.Data.Entities.StrategyConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AdxPeriod")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AdxThreshold")
                        .HasPrecision(9, 4)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("EmaFastPeriod")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EmaSlowPeriod")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EmaTrendPeriod")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExtendedParametersJson")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxFeedDelaySeconds")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MaxSpread")
                        .HasPrecision(18, 8)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MaxWickPercentage")
                        .HasPrecision(9, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MinBodyPercentage")
                        .HasPrecision(9, 4)
                        .HasColumnType("TEXT");

                    b.Property<int>("MinConfidence")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MinRelativeVolume")
                        .HasPrecision(9, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("RsiOverbought")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RsiOversold")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RsiPeriod")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SignalCooldownSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SupportResistanceDistancePips")
                        .HasPrecision(9, 4)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("StrategyConfigurations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdxPeriod = 14,
                            AdxThreshold = 20m,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmaFastPeriod = 20,
                            EmaSlowPeriod = 50,
                            EmaTrendPeriod = 200,
                            IsActive = true,
                            MaxFeedDelaySeconds = 5,
                            MaxSpread = 0.0005m,
                            MaxWickPercentage = 40m,
                            MinBodyPercentage = 50m,
                            MinConfidence = 65,
                            MinRelativeVolume = 1.2m,
                            Name = "Default Volume Pressure Strategy",
                            RsiOverbought = 70,
                            RsiOversold = 30,
                            RsiPeriod = 14,
                            SignalCooldownSeconds = 30,
                            SupportResistanceDistancePips = 5m,
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Version = "1.0.0"
                        });
                });

            modelBuilder.Entity("FXVolumeTrader.Infrastructure.Data.Entities.TickRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Ask")
                        .HasPrecision(18, 8)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Bid")
                        .HasPrecision(18, 8)
                        .HasColumnType("TEXT");

                    b.Property<string>("DataSource")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<int>("Direction")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Last")
                        .HasPrecision(18, 8)
                        .HasColumnType("TEXT");

                    b.Property<long>("SequenceNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TradingSessionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TradingSessionId");

                    b.HasIndex("Symbol", "TimestampUtc");

                    b.ToTable("TickRecords", (string)null);
                });

            modelBuilder.Entity("FXVolumeTrader.Infrastructure.Data.Entities.TradeRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Asset")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("DataSource")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Direction")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("EntryPrice")
                        .HasPrecision(18, 8)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ExitPrice")
                        .HasPrecision(18, 8)
                        .HasColumnType("TEXT");

                    b.Property<int>("Expiry")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MarketCondition")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Payout")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ProfitLoss")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("Result")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ScreenshotPath")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SignalConfidence")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("SignalId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SignalReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("StrategyVersion")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int>("Timeframe")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TradeIdExternal")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TradingSessionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DateUtc");

                    b.HasIndex("Result");

                    b.HasIndex("SignalId");

                    b.HasIndex("TradingSessionId");

                    b.ToTable("TradeRecords", (string)null);
                });

            modelBuilder.Entity("FXVolumeTrader.Infrastructure.Data.Entities.TradingSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Draws")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("EndingBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("Losses")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mode")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("NetResult")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("StartingBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalTrades")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Wins")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TradingSessions", (string)null);
                });

            modelBuilder.Entity("FXVolumeTrader.Infrastructure.Data.Entities.Backtest", b =>
                {
                    b.HasOne("FXVolumeTrader.Infrastructure.Data.Entities.StrategyConfiguration", "StrategyConfiguration")
                        .WithMany("Backtests")
                        .HasForeignKey("StrategyConfigurationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("StrategyConfiguration");
                });

            modelBuilder.Entity("FXVolumeTrader.Infrastructure.Data.Entities.BacktestTrade", b =>
                {
                    b.HasOne("FXVolumeTrader.Infrastructure.Data.Entities.Backtest", "Backtest")
                        .WithMany("Trades")
                        .HasForeignKey("BacktestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Backtest");
                });

            modelBuilder.Entity("FXVolumeTrader.Infrastructure.Data.Entities.RiskEvent", b =>
                {
                    b.HasOne("FXVolumeTrader.Infrastructure.Data.Entities.TradingSession", "TradingSession")
                        .WithMany("RiskEvents")
                        .HasForeignKey("TradingSessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("TradingSession");
                });

            modelBuilder.Entity("FXVolumeTrader.Infrastructure.Data.Entities.Signal", b =>
                {
                    b.HasOne("FXVolumeTrader.Infrastructure.Data.Entities.Candle", "Candle")
                        .WithMany("Signals")
                        .HasForeignKey("CandleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FXVolumeTrader.Infrastructure.Data.Entities.TradingSession", "TradingSession")
                        .WithMany()
                        .HasForeignKey("TradingSessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Candle");

                    b.Navigation("TradingSession");
                });

            modelBuilder.Entity("FXVolumeTrader.Infrastructure.Data.Entities.SignalScoreComponent", b =>
                {
                    b.HasOne("FXVolumeTrader.Infrastructure.Data.Entities.Signal", "Signal")
                        .WithMany("ScoreComponents")
                        .HasForeignKey("SignalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Signal");
                });

            modelBuilder.Entity("FXVolumeTrader.Infrastructure.Data.Entities.TickRecord", b =>
                {
                    b.HasOne("FXVolumeTrader.Infrastructure.Data.Entities.TradingSession", "TradingSession")
                        .WithMany()
                        .HasForeignKey("TradingSessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("TradingSession");
                });

            modelBuilder.Entity("FXVolumeTrader.Infrastructure.Data.Entities.TradeRecord", b =>
                {
                    b.HasOne("FXVolumeTrader.Infrastructure.Data.Entities.Signal", "Signal")
                        .WithMany()
                        .HasForeignKey("SignalId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FXVolumeTrader.Infrastructure.Data.Entities.TradingSession", "TradingSession")
                        .WithMany("Trades")
                        .HasForeignKey("TradingSessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Signal");

                    b.Navigation("TradingSession");
                });

            modelBuilder.Entity("FXVolumeTrader.Infrastructure.Data.Entities.Backtest", b =>
                {
                    b.Navigation("Trades");
                });

            modelBuilder.Entity("FXVolumeTrader.Infrastructure.Data.Entities.Candle", b =>
                {
                    b.Navigation("Signals");
                });

            modelBuilder.Entity("FXVolumeTrader.Infrastructure.Data.Entities.Signal", b =>
                {
                    b.Navigation("ScoreComponents");
                });

            modelBuilder.Entity("FXVolumeTrader.Infrastructure.Data.Entities.StrategyConfiguration", b =>
                {
                    b.Navigation("Backtests");
                });

            modelBuilder.Entity("FXVolumeTrader.Infrastructure.Data.Entities.TradingSession", b =>
                {
                    b.Navigation("RiskEvents");

                    b.Navigation("Trades");
                });
#pragma warning restore 612, 618
        }
    }
}
