<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>ZarghoonJewelryPro</RootNamespace>
    <AssemblyName>ZarghoonJewelryPro</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MySql.Data" Version="8.3.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Forms\frmLogin.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Forms\frmDashboard.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Forms\frmCustomer.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Forms\frmStock.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Forms\frmSales.cs">
      <SubType>Form</SubType>
    </Compile>
  </ItemGroup>

</Project>
