using SQLite;
using GoldBusinessManager.Core.Enums;

namespace GoldBusinessManager.Core.Entities;

[Table("SalesInvoices")]
public class SalesInvoice
{
    [PrimaryKey, AutoIncrement]
    public int Id { get; set; }

    /// <summary>Auto-generated, e.g. "INV-0001". Generated by InvoiceNumberGenerator.</summary>
    [Indexed(Unique = true), NotNull, MaxLength(30)]
    public string InvoiceNumber { get; set; } = string.Empty;

    public DateTime InvoiceDate { get; set; } = DateTime.Now;

    /// <summary>Nullable: a walk-in customer may not be saved in the Customers table.</summary>
    public int? CustomerId { get; set; }

    [NotNull, MaxLength(150)]
    public string CustomerName { get; set; } = string.Empty;

    [MaxLength(20)]
    public string CustomerMobile { get; set; } = string.Empty;

    public ItemType ItemType { get; set; }

    /// <summary>Only used when ItemType == Custom.</summary>
    [MaxLength(100)]
    public string? ItemTypeCustomName { get; set; }

    /// <summary>Weight exactly as typed by the user, in WeightUnit.</summary>
    public double WeightInput { get; set; }

    public WeightUnit WeightUnit { get; set; }

    /// <summary>WeightInput converted to grams. This is the only weight ever used in calculations/stock.</summary>
    public double WeightInGrams { get; set; }

    /// <summary>24K gold rate per gram at the time of sale.</summary>
    public double GoldRatePerGram { get; set; }

    public double MakingCharges { get; set; }

    public double Discount { get; set; }

    /// <summary>GoldAmount = WeightInGrams * GoldRatePerGram.</summary>
    public double GoldAmount { get; set; }

    /// <summary>FinalTotal = GoldAmount + MakingCharges - Discount.</summary>
    public double FinalTotal { get; set; }

    public double ReceivedAmount { get; set; }

    /// <summary>Balance = FinalTotal - ReceivedAmount. Added to the customer ledger.</summary>
    public double BalanceAmount { get; set; }

    public PaymentMethod PaymentMethod { get; set; }

    /// <summary>Portion of ReceivedAmount that went to cash (used when PaymentMethod == Mixed).</summary>
    public double CashAmount { get; set; }

    /// <summary>Portion of ReceivedAmount that went to a bank account (used when PaymentMethod == Mixed).</summary>
    public double BankAmount { get; set; }

    /// <summary>Which bank account received BankAmount, when PaymentMethod is Bank or Mixed.</summary>
    public int? BankAccountId { get; set; }

    [MaxLength(500)]
    public string? Notes { get; set; }

    public DateTime CreatedAt { get; set; } = DateTime.Now;

    public DateTime? UpdatedAt { get; set; }

    /// <summary>Soft delete so deleted invoices can still be audited; stock/ledger effects are reversed on delete.</summary>
    public bool IsDeleted { get; set; }
}
